### PR TITLE
Use dynamic response channels to avoid responses going to every client

### LINKED ISSUE #407: request-response cycle does NxN work when it could do Nx1
I noticed that when a request for all sockets is issued every client gets the request (expected), and every client gets the response (hmmm?). The clients getting every response means we're consuming NxN resources for something that could be done with N.

https://github.com/socketio/socket.io-redis-adapter/blob/3242d8e91baf94720df256ab422ec5c037f6a9e1/lib/index.ts#L195

This seems to be because the response channel is singular^. A path forward could be to have the request originator start listening on a channel associated with the request id then have the responses come through this temporary channel.

### PR DESCRIPTION
**Pull request by doodlesbykumbi**
Resolves #407 

Dynamic response channels are subscribed to, by the request-originator, just before the request is dispatched. This ensures that responses are consumed only by the originator, avoiding unnecessary noise for the other clients.

### CODE REVIEW

**Comment by y4my4my4m** [comment]
I haven't tested it but, if this works as described, would be a great performance boost!

@doodlesbykumbi are the dynamic response automatic or do you need to modify server code to keep track of subscribed channels?

**Comment by doodlesbykumbi** [comment]
@y4my4my4m The dynamic response is automatic. The idea is
1. Client creates request and subscribes to response channel (`prefix + "-response#" + this.nsp.name + "#" + requestId`)
2. Client sends request
3. Clients either times out or gets all the responses it needs
4. Client unsubscribes from response channel

It's a mostly transparent change for consumers of the adapter. It could be made entirely transparent by having it be backwards compatible, but I think it's better to just go all in.

**Comment by darrachequesne** [comment]
@doodlesbykumbi thanks for the pull request! If I understand correctly, this change is not backward compatible and will require a synchronized cluster update, isn't it?

**Comment by doodlesbykumbi** [comment]
I think to maintain backwards compatibility just before dispatching requests we would also have to listen on the original response channel. When we publish a response it would also have to be published on the original response channel.

An edge case (for when dispatching requests) I have to figure out is what happens when by some luck multiple requests take place at the same time. I suppose we'll have to keep a count, and only clean up when the count goes back to 0

**Comment by darrachequesne** [comment]
Superseded by https://github.com/socketio/socket.io-redis-adapter/commit/f66de114a4581b692da759015def0373c619aab7.

**Pull request closed without merging**
